dataset: core50
model: simplebaseline
fast_dev_run: false
debug_mode: false
method: ft-nme

# backbone
convnet_config:
  model_name: vit_base_patch16_224 # vit_base_patch16_224, vit_base_patch16_224_in21k
  pretrained: true

# Misc
batch_size: 64
eval_type: cnn
start_epoch: 1
epochs: 1
workers: 16
build_examplars_every_x_epochs: False
eval_every_x_epochs: 4
check_loss: false
# save_model: last

# logger
label: ft-nme
exp_notes: ft-nme
tags: []
