dataset: imagenet_r
model: simplebaseline
fast_dev_run: false
debug_mode: false
method: ft-seq

# backbone
convnet_config:
  model_name: vit_base_patch16_224 # vit_base_patch16_224, vit_base_patch16_224_in21k
  pretrained: true
  num_classes: 200

# optimizer
grad_clip_norm: 1.0
optimizer:
  opt: adam
  opt_eps: 0.00000001 # 1e-8
  opt_betas: [0.9, 0.999]
  clip_grad: 1.0
  momentum: 0.9
  weight_decay: 0.0
  lr: 0.000005

lr_scheduler:
  method: constant
  lr_decay_rate: 0.1
  lr_decay_epochs: [700, 800, 900]

# Misc
batch_size: 64
eval_type: cnn
start_epoch: 50
epochs: 50
workers: 16
build_examplars_every_x_epochs: False
eval_every_x_epochs: 4
check_loss: false
# save_model: last

# logger
label: ft-seq
exp_notes: ft-seq
tags: []
