#!/bin/bash
# python main.py --config=./configs/cllora/cllora_cifar_B0_Inc5.json
# python main.py --config=./configs/cllora/cllora_cifar_B0_Inc10.json
# python main.py --config=./configs/cllora/cllora_cifar_B0_Inc20.json
# python main.py --config=./configs/cllora/cllora_cifar_B50_Inc5.json
# python main.py --config=./configs/cllora/cllora_cifar_B50_Inc10.json
# python main.py --config=./configs/cllora/cllora_cub_B0_Inc5.json
# python main.py --config=./configs/cllora/cllora_cub_B0_Inc10.json
# python main.py --config=./configs/cllora/cllora_cub_B0_Inc20.json
# python main.py --config=./configs/cllora/cllora_cub_B0_Inc40.json
# python main.py --config=./configs/cllora/cllora_cub_B100_Inc5.json
# python main.py --config=./configs/cllora/cllora_cub_B100_Inc10.json
# python main.py --config=./configs/cllora/cllora_cub_B100_Inc20.json
# python main.py --config=./configs/cllora/cllora_inr_B0_Inc5.json
# python main.py --config=./configs/cllora/cllora_inr_B0_Inc10.json
# python main.py --config=./configs/cllora/cllora_inr_B0_Inc20.json
# python main.py --config=./configs/cllora/cllora_inr_B0_Inc40.json
# python main.py --config=./configs/cllora/cllora_inr_B100_Inc5.json
# python main.py --config=./configs/cllora/cllora_inr_B100_Inc10.json
# python main.py --config=./configs/cllora/cllora_inr_B100_Inc20.json
# python main.py --config=./configs/cllora/cllora_ina_B0_Inc5.json
 python main.py --config=./configs/cllora/cllora_ina_B0_Inc10.json
 python main.py --config=./configs/cllora/cllora_ina_B0_Inc20.json
 python main.py --config=./configs/cllora/cllora_ina_B0_Inc40.json
 python main.py --config=./configs/cllora/cllora_ina_B100_Inc5.json
 python main.py --config=./configs/cllora/cllora_ina_B100_Inc10.json
 python main.py --config=./configs/cllora/cllora_ina_B100_Inc20.json
 python main.py --config=./configs/cllora/cllora_omni_B0_Inc5.json
 python main.py --config=./configs/cllora/cllora_omni_B0_Inc10.json
 python main.py --config=./configs/cllora/cllora_omni_B0_Inc20.json
 python main.py --config=./configs/cllora/cllora_omni_B0_Inc30.json
 python main.py --config=./configs/cllora/cllora_omni_B150_Inc5.json
 python main.py --config=./configs/cllora/cllora_omni_B150_Inc10.json
 python main.py --config=./configs/cllora/cllora_omni_B150_Inc30.json
 python main.py --config=./configs/cllora/cllora_vtab_B0_Inc5.json
 python main.py --config=./configs/cllora/cllora_vtab_B0_Inc10.json
 python main.py --config=./configs/cllora/cllora_domainnet_B0_Inc69.json